### ISSUE TITLE
Writing to PWM

### ISSUE THREAD

**Issue by smarquis** [jadonk/bonescript#114] opened 2016-02-11 02:22 UTC
Hi,

When i try to execute the following js code:
var b = require('bonescript');    
b.analogWrite('P8_34',0.7,200.0,console.log);

I get the following error code:

error: error updating PWM freq and value: undefined, Error: ENOENT, no such file or directory 'undefined/duty'
{ err: 'error updating PWM freq and value: undefined, Error: ENOENT, no such file or directory \'undefined/duty\'' }

I've installed fresh images, ran update, upgrades, and attempted all sort of work arounds. This problem shouldn't be persisting across completely fresh images. Is there a workaround to this?

Thanks for any help!

p.s. The PWM's work fine through adafruits BBIO library when i call on PWM output in python, but I need these PWM call to be in JS.

**Comment by MarkAYoder** [comment] 2016-02-11 15:25
I  there are two things happening here.  Have you disabled the HDMI?  If not, pin P8_34 is used by it.  I think that's why there is an 'undefined' in the path.

The second thing is a bug I fixed.  It turns out when the pwm is first used you have to change the period before changing the duty cycle.

This should be fixed now.  The fix is in my repo[1] waiting for Jason to pull it in.

--Mark

[1] https://github.com/MarkAYoder/bonescript

**Comment by jadonk** [comment] 2016-02-14 05:01
Merged into 0.5.x branch.

**Comment by kory44** [comment] 2016-03-07 00:47
I'm(noob) so confused, how do i get the version of bonescript on my BBB so that it will correctly do PWM?

like, what is the actual command? I have debian 7.9.

**Comment by sputnik63** [comment] 2016-05-17 10:09
If hw_oldkernel.js is used by bonescript maybe this issue could be caused by the issue #128

**Comment by jadonk** [comment] 2016-05-18 13:33
@smarquis Can I close this one?

**Comment by smarquis** [comment] 2016-05-18 13:36
Hi @jadonk 

You can close this issue. It has been resolved :) thanks @MarkAYoder for the help!

**Closed** 2016-05-18 13:56 UTC
